
spring:
  data:
    mongodb:
      username: cbgomes
      password: cbgomes
      host: localhost
      port: 27017
      database: customers
      authentication-database: admin

server:
  port: 8090