services:
  postgresql:
    container_name: ms_ecommerce_acme
    image: postgres
    environment:
      POSTGRES_DB: ms_ecommerce_acme
      POSTGRES_USER: cbgomes
      POSTGRES_PASSWORD: cbgomes
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5455:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  mail-dev:
    container_name: ecommerce-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: cbgomes
      MONGO_INITDB_ROOT_PASSWORD: cbgomes


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cbgomes
      ME_CONFIG_MONGODB_ADMINPASSWORD: cbgomes
      ME_CONFIG_MONGODB_URL: mongodb://cbgomes:cbgomes@mongo:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  mongo: