server:
  port: 8888
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cbgomesfilho/config-server.git
          default-label: master
          search-paths:
            - config-server

